import type { Roaster, Campaign, AutomationRule, CoffeeLot, SampleKit, Order, WebhookSubscriptionWithSecret, Reservation } from '../types/api';

export const db = {
  roasters: [] as Roaster[],
  campaigns: [] as Campaign[],
  rules: [] as AutomationRule[],
  lots: [] as CoffeeLot[],
  sampleKits: [] as SampleKit[],
  orders: [] as Order[],
  reservations: [] as Reservation[],
  webhooks: [] as WebhookSubscriptionWithSecret[],
  idempotency: new Map<string, { bodyHash: string; response: unknown; problem?: unknown }>(),
};

export function seedDatabase() {
  db.idempotency.clear();

  db.lots = [
    {
      id: 'lot_001',
      origin: 'Huila, Colombia',
      varietal: 'Pink Bourbon',
      processingMethod: 'washed',
      elevation: 1750,
      cupScore: 88.5,
      pricePerLbCents: 610,
      costPerLbCents: 445,
      availableQuantityLbs: 2640,
      totalProductionLbs: 6600,
      esgScore: 0.82,
      logisticsScore: 0.78,
      certifications: { fairTrade: false, organic: true, rainforestAlliance: false },
      flavorNotes: ['jasmine', 'cane sugar', 'red currant', 'cocoa nib', 'lime'],
      sensoryProfile: { acidity: 8.5, body: 7.0, sweetness: 8.8 },
      portOfOrigin: 'Buenaventura',
      estimatedArrival: '2025-07-12',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
    {
      id: 'lot_002',
      origin: 'Yirgacheffe, Ethiopia',
      varietal: 'Heirloom',
      processingMethod: 'natural',
      elevation: 2100,
      cupScore: 87.0,
      pricePerLbCents: 575,
      costPerLbCents: 410,
      availableQuantityLbs: 1320,
      totalProductionLbs: 4400,
      esgScore: 0.78,
      logisticsScore: 0.72,
      certifications: { fairTrade: true, organic: false, rainforestAlliance: false },
      flavorNotes: ['blueberry', 'bergamot', 'cacao', 'lavender'],
      sensoryProfile: { acidity: 8.8, body: 7.5, sweetness: 8.4 },
      portOfOrigin: 'Djibouti',
      estimatedArrival: '2025-06-28',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
    {
      id: 'lot_003',
      origin: 'Tarrazú, Costa Rica',
      varietal: 'Caturra',
      processingMethod: 'honey',
      elevation: 1850,
      cupScore: 86.5,
      pricePerLbCents: 520,
      costPerLbCents: 380,
      availableQuantityLbs: 3960,
      totalProductionLbs: 8800,
      esgScore: 0.85,
      logisticsScore: 0.80,
      certifications: { fairTrade: false, organic: false, rainforestAlliance: true },
      flavorNotes: ['chocolate', 'orange zest', 'panela', 'almond', 'vanilla', 'black tea'],
      sensoryProfile: { acidity: 7.8, body: 8.0, sweetness: 8.6 },
      portOfOrigin: 'Puerto Limón',
      estimatedArrival: '2025-06-30',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
    {
      id: 'lot_004',
      origin: 'Nyeri, Kenya',
      varietal: 'SL28',
      processingMethod: 'washed',
      elevation: 1900,
      cupScore: 90.5,
      pricePerLbCents: 980,
      costPerLbCents: 720,
      availableQuantityLbs: 880,
      totalProductionLbs: 2200,
      esgScore: 0.74,
      logisticsScore: 0.75,
      certifications: { fairTrade: false, organic: false, rainforestAlliance: false },
      flavorNotes: ['blackcurrant', 'grapefruit', 'brown sugar', 'tomato leaf'],
      sensoryProfile: { acidity: 9.2, body: 7.8, sweetness: 8.9 },
      portOfOrigin: 'Mombasa',
      estimatedArrival: '2025-08-03',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
    {
      id: 'lot_005',
      origin: 'Cajamarca, Peru',
      varietal: 'Bourbon',
      processingMethod: 'anaerobic',
      elevation: 1950,
      cupScore: 84.0,
      pricePerLbCents: 460,
      costPerLbCents: 330,
      availableQuantityLbs: 0,
      totalProductionLbs: 3300,
      esgScore: 0.88,
      logisticsScore: 0.77,
      certifications: { fairTrade: false, organic: true, rainforestAlliance: false },
      flavorNotes: ['rum raisin', 'pineapple', 'cinnamon'],
      sensoryProfile: { acidity: 8.2, body: 7.2, sweetness: 8.0 },
      portOfOrigin: 'Callao',
      estimatedArrival: '2025-07-20',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
  ];

  db.roasters = [
    {
      id: 'r_001',
      roasterName: 'Blue Bottle Coffee',
      segment: 'commercial',
      status: 'active',
      churnRiskScore: 0.12,
      ltvCents: 12450000,
      cacCents: 85000,
      paybackMonths: 4,
      daysSinceLastOrder: 5,
      totalRevenueCents: 12450000,
      totalOrders: 42,
      billingCycle: 'annual',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'J. Doe', email: 'j@bluebottle.com', marketingOptIn: true },
      interventions: [
        { id: 'i1', type: 'sales_call', date: '2025-06-10', outcome: 'retained', notes: 'Scheduled annual contract renewal meeting.' },
      ],
    },
    {
      id: 'r_002',
      roasterName: 'Heart Coffee Roasters',
      segment: 'boutique',
      status: 'active',
      churnRiskScore: 0.28,
      ltvCents: 2450000,
      cacCents: 38000,
      paybackMonths: 6,
      daysSinceLastOrder: 14,
      totalRevenueCents: 2450000,
      totalOrders: 18,
      billingCycle: 'quarterly',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'A. Smith', email: 'a@heartcoffee.com', marketingOptIn: true },
      interventions: [
        { id: 'i2', type: 'email_campaign', date: '2025-06-15', outcome: 'retained', notes: 'FOB price threshold alert sent.' },
      ],
    },
    {
      id: 'r_003',
      roasterName: 'Coava Coffee Roasters',
      segment: 'boutique',
      status: 'dormant',
      churnRiskScore: 0.74,
      ltvCents: 1820000,
      cacCents: 42000,
      paybackMonths: 8,
      daysSinceLastOrder: 45,
      totalRevenueCents: 1820000,
      totalOrders: 12,
      billingCycle: 'quarterly',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'B. Brown', email: 'b@coava.com', marketingOptIn: true },
      interventions: [
        { id: 'i3', type: 'discount_offer', date: '2025-06-20', outcome: 'pending', notes: 'Offered 10% sample kit discount on Nyeri Kenya lot.' },
        { id: 'i4', type: 'sales_call', date: '2025-05-18', outcome: 'retained', notes: 'Initial check-in regarding quality dissatisfaction.' },
      ],
    },
    {
      id: 'r_004',
      roasterName: 'Metric Coffee Co.',
      segment: 'micro',
      status: 'trial',
      churnRiskScore: 0.45,
      ltvCents: 420000,
      cacCents: 12000,
      paybackMonths: 3,
      daysSinceLastOrder: 3,
      totalRevenueCents: 420000,
      totalOrders: 3,
      billingCycle: 'monthly',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'C. White', email: 'c@metriccoffee.com', marketingOptIn: false },
      interventions: [
        { id: 'i5', type: 'survey', date: '2025-06-25', outcome: 'pending', notes: 'Onboarding survey sent via automatic flow.' },
      ],
    },
    {
      id: 'r_005',
      roasterName: 'Stumptown Coffee',
      segment: 'commercial',
      status: 'churned',
      churnRiskScore: 0.95,
      ltvCents: 9540000,
      cacCents: 85000,
      paybackMonths: 9,
      daysSinceLastOrder: 120,
      totalRevenueCents: 9540000,
      totalOrders: 31,
      billingCycle: 'annual',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'D. Black', email: 'd@stumptown.com', marketingOptIn: true },
      interventions: [
        { id: 'i6', type: 'discount_offer', date: '2025-04-12', outcome: 'churned', notes: 'Attempted save offer. No response.' },
      ],
    },
  ];

  db.campaigns = [
    {
      id: 'c_001',
      slug: 'cof-nurture-2025',
      name: 'COF Nurture 2025',
      status: 'active',
      version: 1,
      ruleCodes: ['COF-001', 'COF-002', 'COF-003', 'COF-004', 'COF-005'],
      targetAudience: { segments: ['micro', 'boutique'], minCupScorePreference: 85 },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  db.rules = [
    {
      id: 'rule_001',
      ruleCode: 'COF-001',
      campaignId: 'c_001',
      ruleName: 'Touch 1 — Origin story after kit delivery',
      triggerEvent: 'sample_kit.delivered',
      conditionsJson: { days_since_delivery: 4 },
      version: 1,
      status: 'armed',
      actions: [{ actionType: 'SEND_TEMPLATE', templateId: 'tmpl_001', channel: 'email', delayMinutes: 0 }],
    },
    {
      id: 'rule_002',
      ruleCode: 'COF-002',
      campaignId: 'c_001',
      ruleName: 'Touch 2 — Brewing guide after kit delivery',
      triggerEvent: 'sample_kit.delivered',
      conditionsJson: { days_since_delivery: 7 },
      version: 1,
      status: 'armed',
      actions: [{ actionType: 'SEND_TEMPLATE', templateId: 'tmpl_002', channel: 'email', delayMinutes: 0 }],
    },
    {
      id: 'rule_003',
      ruleCode: 'COF-003',
      campaignId: 'c_001',
      ruleName: 'Touch 3 — Feedback request',
      triggerEvent: 'sample_kit.delivered',
      conditionsJson: { days_since_delivery: 14 },
      version: 1,
      status: 'armed',
      actions: [{ actionType: 'SEND_TEMPLATE', templateId: 'tmpl_003', channel: 'email', delayMinutes: 0 }],
    },
    {
      id: 'rule_004',
      ruleCode: 'COF-004',
      campaignId: 'c_001',
      ruleName: 'Touch 4 — Re-engagement if no order placed',
      triggerEvent: 'roaster.no_order',
      conditionsJson: { days_since_last_order: 21 },
      version: 1,
      status: 'armed',
      actions: [{ actionType: 'SEND_TEMPLATE', templateId: 'tmpl_004', channel: 'email', delayMinutes: 0 }],
    },
    {
      id: 'rule_005',
      ruleCode: 'COF-005',
      campaignId: 'c_001',
      ruleName: 'Touch 5 — Final nurture offer',
      triggerEvent: 'roaster.no_order',
      conditionsJson: { days_since_last_order: 30 },
      version: 1,
      status: 'armed',
      actions: [{ actionType: 'SEND_TEMPLATE', templateId: 'tmpl_005', channel: 'email', delayMinutes: 0 }],
    },
  ];

  db.orders = [];
  db.reservations = [];
  db.sampleKits = [];
  db.webhooks = [];
}

export function resetDatabase() {
  seedDatabase();
}
