import type { Roaster, Campaign, AutomationRule, CoffeeLot, SampleKit, Order, WebhookSubscriptionWithSecret, Reservation } from '../types/api';
import type { MarketingTemplate } from '../types/marketing';
import { MARKETING_TEMPLATES } from './marketing-data';

export const db = {
  roasters: [] as Roaster[],
  campaigns: [] as Campaign[],
  rules: [] as AutomationRule[],
  templates: [] as MarketingTemplate[],
  lots: [] as CoffeeLot[],
  sampleKits: [] as SampleKit[],
  orders: [] as Order[],
  reservations: [] as Reservation[],
  webhooks: [] as WebhookSubscriptionWithSecret[],
  idempotency: new Map<string, { bodyHash: string; response: unknown; problem?: unknown }>(),
};

export function seedDatabase() {
  db.idempotency.clear();

  db.lots = [
    {
      id: 'lot_001',
      origin: 'Huila, Colombia',
      varietal: 'Pink Bourbon',
      processingMethod: 'washed',
      elevation: 1750,
      cupScore: 88.5,
      pricePerLbCents: 610,
      costPerLbCents: 445,
      availableQuantityLbs: 2640,
      totalProductionLbs: 6600,
      esgScore: 0.82,
      logisticsScore: 0.78,
      certifications: { fairTrade: false, organic: true, rainforestAlliance: false },
      flavorNotes: ['jasmine', 'cane sugar', 'red currant', 'cocoa nib', 'lime'],
      sensoryProfile: { acidity: 8.5, body: 7.0, sweetness: 8.8 },
      portOfOrigin: 'Buenaventura',
      estimatedArrival: '2025-07-12',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
    {
      id: 'lot_002',
      origin: 'Yirgacheffe, Ethiopia',
      varietal: 'Heirloom',
      processingMethod: 'natural',
      elevation: 2100,
      cupScore: 87.0,
      pricePerLbCents: 575,
      costPerLbCents: 410,
      availableQuantityLbs: 1320,
      totalProductionLbs: 4400,
      esgScore: 0.78,
      logisticsScore: 0.72,
      certifications: { fairTrade: true, organic: false, rainforestAlliance: false },
      flavorNotes: ['blueberry', 'bergamot', 'cacao', 'lavender'],
      sensoryProfile: { acidity: 8.8, body: 7.5, sweetness: 8.4 },
      portOfOrigin: 'Djibouti',
      estimatedArrival: '2025-06-28',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
    {
      id: 'lot_003',
      origin: 'Tarrazú, Costa Rica',
      varietal: 'Caturra',
      processingMethod: 'honey',
      elevation: 1850,
      cupScore: 86.5,
      pricePerLbCents: 520,
      costPerLbCents: 380,
      availableQuantityLbs: 3960,
      totalProductionLbs: 8800,
      esgScore: 0.85,
      logisticsScore: 0.80,
      certifications: { fairTrade: false, organic: false, rainforestAlliance: true },
      flavorNotes: ['chocolate', 'orange zest', 'panela', 'almond', 'vanilla', 'black tea'],
      sensoryProfile: { acidity: 7.8, body: 8.0, sweetness: 8.6 },
      portOfOrigin: 'Puerto Limón',
      estimatedArrival: '2025-06-30',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
    {
      id: 'lot_004',
      origin: 'Nyeri, Kenya',
      varietal: 'SL28',
      processingMethod: 'washed',
      elevation: 1900,
      cupScore: 90.5,
      pricePerLbCents: 980,
      costPerLbCents: 720,
      availableQuantityLbs: 880,
      totalProductionLbs: 2200,
      esgScore: 0.74,
      logisticsScore: 0.75,
      certifications: { fairTrade: false, organic: false, rainforestAlliance: false },
      flavorNotes: ['blackcurrant', 'grapefruit', 'brown sugar', 'tomato leaf'],
      sensoryProfile: { acidity: 9.2, body: 7.8, sweetness: 8.9 },
      portOfOrigin: 'Mombasa',
      estimatedArrival: '2025-08-03',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
    {
      id: 'lot_005',
      origin: 'Cajamarca, Peru',
      varietal: 'Bourbon',
      processingMethod: 'anaerobic',
      elevation: 1950,
      cupScore: 84.0,
      pricePerLbCents: 460,
      costPerLbCents: 330,
      availableQuantityLbs: 0,
      totalProductionLbs: 3300,
      esgScore: 0.88,
      logisticsScore: 0.77,
      certifications: { fairTrade: false, organic: true, rainforestAlliance: false },
      flavorNotes: ['rum raisin', 'pineapple', 'cinnamon'],
      sensoryProfile: { acidity: 8.2, body: 7.2, sweetness: 8.0 },
      portOfOrigin: 'Callao',
      estimatedArrival: '2025-07-20',
      status: 'active',
      lastUpdatedAt: new Date().toISOString(),
    },
  ];

  db.roasters = [
    {
      id: 'r_001',
      roasterName: 'Blue Bottle Coffee',
      segment: 'commercial',
      status: 'active',
      churnRiskScore: 0.12,
      ltvCents: 12450000,
      cacCents: 85000,
      paybackMonths: 4,
      daysSinceLastOrder: 5,
      totalRevenueCents: 12450000,
      totalOrders: 42,
      billingCycle: 'annual',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'J. Doe', email: 'j@bluebottle.com', marketingOptIn: true },
      interventions: [
        { id: 'i1', type: 'sales_call', date: '2025-06-10', outcome: 'retained', notes: 'Scheduled annual contract renewal meeting.' },
      ],
    },
    {
      id: 'r_002',
      roasterName: 'Heart Coffee Roasters',
      segment: 'boutique',
      status: 'active',
      churnRiskScore: 0.28,
      ltvCents: 2450000,
      cacCents: 38000,
      paybackMonths: 6,
      daysSinceLastOrder: 14,
      totalRevenueCents: 2450000,
      totalOrders: 18,
      billingCycle: 'quarterly',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'A. Smith', email: 'a@heartcoffee.com', marketingOptIn: true },
      interventions: [
        { id: 'i2', type: 'email_campaign', date: '2025-06-15', outcome: 'retained', notes: 'FOB price threshold alert sent.' },
      ],
    },
    {
      id: 'r_003',
      roasterName: 'Coava Coffee Roasters',
      segment: 'boutique',
      status: 'dormant',
      churnRiskScore: 0.74,
      ltvCents: 1820000,
      cacCents: 42000,
      paybackMonths: 8,
      daysSinceLastOrder: 45,
      totalRevenueCents: 1820000,
      totalOrders: 12,
      billingCycle: 'quarterly',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'B. Brown', email: 'b@coava.com', marketingOptIn: true },
      interventions: [
        { id: 'i3', type: 'discount_offer', date: '2025-06-20', outcome: 'pending', notes: 'Offered 10% sample kit discount on Nyeri Kenya lot.' },
        { id: 'i4', type: 'sales_call', date: '2025-05-18', outcome: 'retained', notes: 'Initial check-in regarding quality dissatisfaction.' },
      ],
    },
    {
      id: 'r_004',
      roasterName: 'Metric Coffee Co.',
      segment: 'micro',
      status: 'trial',
      churnRiskScore: 0.45,
      ltvCents: 420000,
      cacCents: 12000,
      paybackMonths: 3,
      daysSinceLastOrder: 3,
      totalRevenueCents: 420000,
      totalOrders: 3,
      billingCycle: 'monthly',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'C. White', email: 'c@metriccoffee.com', marketingOptIn: false },
      interventions: [
        { id: 'i5', type: 'survey', date: '2025-06-25', outcome: 'pending', notes: 'Onboarding survey sent via automatic flow.' },
      ],
    },
    {
      id: 'r_005',
      roasterName: 'Stumptown Coffee',
      segment: 'commercial',
      status: 'churned',
      churnRiskScore: 0.95,
      ltvCents: 9540000,
      cacCents: 85000,
      paybackMonths: 9,
      daysSinceLastOrder: 120,
      totalRevenueCents: 9540000,
      totalOrders: 31,
      billingCycle: 'annual',
      lastActivityAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      primaryContact: { fullName: 'D. Black', email: 'd@stumptown.com', marketingOptIn: true },
      interventions: [
        { id: 'i6', type: 'discount_offer', date: '2025-04-12', outcome: 'churned', notes: 'Attempted save offer. No response.' },
      ],
    },
  ];

  const now = new Date().toISOString();

  db.campaigns = [
    {
      id: 'campaign-cof-001',
      slug: 'cof-001',
      name: 'COF-001 — First Crack',
      description: 'Activate new lead → sample kit request.',
      status: 'active',
      version: 1,
      targetAudience: { segments: ['micro', 'boutique'], minCupScorePreference: 55 },
      ruleCodes: ['COF-001'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'campaign-cof-002',
      slug: 'cof-002',
      name: 'COF-002 — The Cupping',
      description: 'Kit delivered → cupping feedback.',
      status: 'active',
      version: 1,
      targetAudience: { segments: ['micro', 'boutique', 'commercial'] },
      ruleCodes: ['COF-002'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'campaign-cof-003',
      slug: 'cof-003',
      name: 'COF-003 — The Shortlist',
      description: 'Feedback → first paid order.',
      status: 'active',
      version: 1,
      targetAudience: { segments: ['micro', 'boutique', 'commercial'] },
      ruleCodes: ['COF-003'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'campaign-cof-004',
      slug: 'cof-004',
      name: 'COF-004 — Second Cup',
      description: 'Rescue non-responders before hard suppression at day 21.',
      status: 'active',
      version: 1,
      targetAudience: { segments: ['micro', 'boutique', 'commercial'] },
      ruleCodes: ['COF-004'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'campaign-cof-005',
      slug: 'cof-005',
      name: 'COF-005 — The Regular',
      description: 'First order → reorder + referral seed.',
      status: 'active',
      version: 1,
      targetAudience: { segments: ['micro', 'boutique', 'commercial'] },
      ruleCodes: ['COF-005'],
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Seeded rule actions use human-readable templateIds (e.g., COF-001-E1) that
  // intentionally bypass the API's UUID ruleCreateSchema because these rules are
  // read-only seed data. Editing them through RuleForm will fail validation.
  db.rules = [
    {
      id: 'rule-cof-001',
      ruleCode: 'COF-001',
      campaignId: 'campaign-cof-001',
      ruleName: 'qualified_lead_first_crack_sequence',
      triggerEvent: 'lead.qualified',
      conditionsJson: {
        lead_score_min: 55,
        segment_in: ['micro', 'boutique'],
        account_status_not_in: ['churned'],
        suppression_check: {
          unsubscribed: false,
          active_campaign_not_in: ['COF-004', 'WIN-001'],
          open_order_in_flight: false,
        },
      },
      version: 1,
      status: 'armed',
      actions: [
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-001-E1', channel: 'email', delayMinutes: 0, payload: { ab_test_id: 'abt_cof001_subject_v1' } },
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-001-E2', channel: 'email', delayMinutes: 4320, payload: { fire_if: { opened_at_is_null: true } } },
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-001-S1', channel: 'sms', delayMinutes: 7200, payload: { fire_if: { opened_at_not_null: true, kit_requested: false } } },
        { actionType: 'UPDATE_CRM_LIFECYCLE', payload: { lifecycle_stage: 'kit_offered', set_fields: { status: 'trial' }, log_to: 'campaign_execution_logs' } },
        { actionType: 'EXECUTE_CAMPAIGN_HALT', payload: { halt_on_event: ['sample_kit.requested', 'user.unsubscribed', 'order.created'], halt_scope: 'campaign_id:COF-001', post_halt_route: { 'sample_kit.requested': 'fulfillment.temporal.kit_workflow' }, reason: 'conversion_or_opt_out' } },
      ],
    },
    {
      id: 'rule-cof-002',
      ruleCode: 'COF-002',
      campaignId: 'campaign-cof-002',
      ruleName: 'kit_delivered_cupping_followup',
      triggerEvent: 'sample_kit.delivered',
      conditionsJson: {
        days_since_delivery: 4,
        feedback_submitted: false,
        suppression_check: { unsubscribed: false, order_created_since_delivery: false },
      },
      version: 1,
      status: 'armed',
      actions: [
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-002-E1', channel: 'email', delayMinutes: 0, payload: { ab_test_id: 'abt_cof002_subject_v1' } },
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-002-S1', channel: 'sms', delayMinutes: 4320, payload: { fire_if: { feedback_submitted: false } } },
        { actionType: 'UPDATE_CRM_LIFECYCLE', payload: { lifecycle_stage: 'kit_cupping_window', set_fields: { last_activity_at: 'now()' }, log_to: 'campaign_execution_logs' } },
        { actionType: 'EXECUTE_CAMPAIGN_HALT', payload: { halt_on_event: ['feedback.submitted', 'order.created', 'user.unsubscribed'], halt_scope: 'campaign_id:COF-002', post_halt_route: { 'feedback.submitted': 'campaign:COF-003', 'order.created': 'campaign:COF-005' }, reason: 'activation_or_conversion' } },
      ],
    },
    {
      id: 'rule-cof-003',
      ruleCode: 'COF-003',
      campaignId: 'campaign-cof-003',
      ruleName: 'feedback_to_first_order',
      triggerEvent: 'feedback.submitted',
      conditionsJson: {
        has_paid_order: false,
        feedback_valence_in: ['positive', 'mixed', 'negative'],
        suppression_check: { unsubscribed: false, open_order_in_flight: false, payment_delinquency_days_max: 0 },
      },
      version: 1,
      status: 'armed',
      actions: [
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-003-E1', channel: 'email', delayMinutes: 120, payload: { ab_test_id: 'abt_cof003_subject_v1', personalization: { branch_on: 'feedback_valence', tokens: ['{flavor_notes}', '{lot_size_bags}', '{price_per_lb}', '{savings_estimate}'] } } },
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-003-E2', channel: 'email', delayMinutes: 7200, payload: { fire_if: { order_created: false } } },
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-003-S1', channel: 'sms', delayMinutes: 14400, payload: { fire_if: { order_created: false } } },
        { actionType: 'UPDATE_CRM_LIFECYCLE', payload: { lifecycle_stage: 'shortlist_presented', set_fields: { days_since_last_order: null }, log_to: 'campaign_execution_logs' } },
        { actionType: 'EXECUTE_CAMPAIGN_HALT', payload: { halt_on_event: ['order.created', 'user.unsubscribed'], halt_scope: 'campaign_id:COF-003', post_halt_route: { 'order.created': 'campaign:COF-005' }, reason: 'first_order_conversion', sla_ms: 300000 } },
      ],
    },
    {
      id: 'rule-cof-004',
      ruleCode: 'COF-004',
      campaignId: 'campaign-cof-004',
      ruleName: 'silent_kit_rescue',
      triggerEvent: 'sample_kit.delivered',
      conditionsJson: {
        days_since_delivery: 9,
        feedback_submitted: false,
        order_created_since_delivery: false,
        suppression_check: { unsubscribed: false, active_campaign_not_in: ['COF-003'], prior_rescue_attempts_max: 0 },
      },
      version: 1,
      status: 'armed',
      actions: [
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-004-E1', channel: 'email', delayMinutes: 0, payload: { ab_test_id: 'abt_cof004_subject_v1' } },
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-004-S1', channel: 'sms', delayMinutes: 7200, payload: { fire_if: { any_structured_response: false } } },
        { actionType: 'UPDATE_CRM_LIFECYCLE', payload: { lifecycle_stage: 'rescue_window', schedule_exit: { at_day: 21, route: 'newsletter.quarterly', set_lead_score_decay: -15 }, log_to: 'campaign_execution_logs' } },
        { actionType: 'EXECUTE_CAMPAIGN_HALT', payload: { halt_on_event: ['feedback.submitted', 'order.created', 'structured_response.logged', 'user.unsubscribed'], halt_scope: 'campaign_id:COF-004', post_halt_route: { 'feedback.submitted': 'campaign:COF-003', 'order.created': 'campaign:COF-005' }, reason: 'rescued_or_resolved' } },
      ],
    },
    {
      id: 'rule-cof-005',
      ruleCode: 'COF-005',
      campaignId: 'campaign-cof-005',
      ruleName: 'first_order_habit_and_advocacy',
      triggerEvent: 'order.delivered',
      conditionsJson: {
        is_first_order: true,
        days_since_delivery: 14,
        suppression_check: { unsubscribed: false, support_ticket_open: false, quality_check_passed: true },
      },
      version: 1,
      status: 'armed',
      actions: [
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-005-E1', channel: 'email', delayMinutes: 0, payload: { ab_test_id: 'abt_cof005_subject_v1', personalization: { tokens: ['{referral_url}', '{origin}', '{process_method}'] } } },
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-005-E2', channel: 'email', delayMinutes: 44640, payload: { fire_if: { reorder_created: false }, personalization: { tokens: ['{first_order_lbs}', '{lot_size_bags}', '{price_per_lb}'] } } },
        { actionType: 'SEND_TEMPLATE', templateId: 'COF-005-S1', channel: 'sms', delayMinutes: 54720, payload: { fire_if: { reorder_created: false, clicked_at_not_null: true } } },
        { actionType: 'UPDATE_CRM_LIFECYCLE', payload: { lifecycle_stage: 'first_order_active', on_reorder: { lifecycle_stage: 'active_repeat', set_fields: { status: 'active' } }, log_to: 'campaign_execution_logs' } },
        { actionType: 'EXECUTE_CAMPAIGN_HALT', payload: { halt_on_event: ['order.created', 'user.unsubscribed'], halt_scope: 'campaign_id:COF-005', halt_note: 'reorder converts lifecycle to active_repeat cadence; referral card persists in-product regardless', reason: 'habit_established' } },
      ],
    },
  ];

  db.templates = MARKETING_TEMPLATES;

  db.orders = [];
  db.reservations = [];
  db.sampleKits = [];
  db.webhooks = [];
}

export function resetDatabase() {
  seedDatabase();
}
